# Generated by Django 4.1.7 on 2023-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_chapter_bannerfilmname_chapter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
