# Generated by Django 4.1.7 on 2023-04-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0005_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilm',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categorys', to='Entity.category'),
        ),
        migrations.AlterField(
            model_name='categoryfilm',
            name='Film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Films', to='Entity.film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='Description',
            field=models.TextField(),
        ),
    ]
