# Generated by Django 4.1.7 on 2023-04-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0007_alter_categoryfilm_category_alter_categoryfilm_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CategoryParent',
        ),
        migrations.AddField(
            model_name='film',
            name='Image',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='categoryfilm',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryfilms', to='Entity.category'),
        ),
    ]
