# Generated by Django 4.1.7 on 2023-04-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0008_remove_category_categoryparent_film_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='HistoryTypeID',
        ),
    ]
