# Generated by Django 4.1.7 on 2023-04-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0009_remove_history_historytypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='Image',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
