# Generated by Django 4.1.7 on 2023-04-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0010_chapter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilm',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryfilm', to='Entity.category'),
        ),
        migrations.AlterField(
            model_name='categoryfilm',
            name='Film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmcategory', to='Entity.film'),
        ),
        migrations.AlterField(
            model_name='history',
            name='Chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapteruser', to='Entity.chapter'),
        ),
        migrations.AlterField(
            model_name='history',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchapter', to='Entity.user'),
        ),
        migrations.AlterField(
            model_name='history',
            name='WatchedTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleuser', to='Entity.role'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='Entity.user'),
        ),
    ]
