# Generated by Django 4.1.7 on 2023-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0012_alter_history_watchedtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='BannerFilmName',
            new_name='ChapterDescription',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='Image',
            new_name='ChapterImage',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='Description',
            new_name='TrailerChapter',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Description',
            new_name='FilmDescription',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Image',
            new_name='FilmImage',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='TrailerFilm',
        ),
        migrations.RemoveField(
            model_name='film',
            name='Video',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='ChapterName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
