# Generated by Django 4.1.7 on 2023-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0013_rename_bannerfilmname_chapter_chapterdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='ChapterCreateDay',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='ChapterPremieredDay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='ChapterStatus',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='TrailerChapter',
            field=models.TextField(),
        ),
    ]
