# Generated by Django 4.1.7 on 2023-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0014_chapter_chaptercreateday_chapter_chapterpremieredday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='BannerFilmName',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='FilmBollen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='FilmDescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='FilmImage',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='film',
            name='TrailerFilm',
            field=models.TextField(default=''),
        ),
    ]
