# Generated by Django 4.1.7 on 2023-04-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0019_history_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorName', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('nativeLand', models.CharField(max_length=225)),
                ('Sex', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ActorFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.actor')),
                ('Film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.film')),
            ],
        ),
    ]
