# Generated by Django 4.1.7 on 2023-04-25 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0021_remove_actorfilm_film_actorfilm_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorfilm',
            name='Chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.chapter'),
        ),
    ]
