# Generated by Django 4.1.7 on 2023-04-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0022_alter_actorfilm_chapter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorFilm',
            new_name='ActorChapter',
        ),
    ]
